# Generated by Django 4.2.2 on 2023-06-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisp_chat', '0002_remove_user__password_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
